apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - image: vigneshvicky12345/demo:13
        imagePullPolicy: Always
        name: apache
        ports:
        - containerPort: 80
  
